FROM nginx:latest
ADD ./Docker/nginx_api.conf /etc/nginx/conf.d/site.conf
ADD ./Docker/id_rsa /root/.ssh/id_rsa
ADD ./Docker/id_rsa.pub /root/.ssh/id_rsa.pub
RUN chmod 600 /root/.ssh/id_rsa

RUN apt-get update \
 && apt-get clean \
 && apt-get install -y curl git vim wget cron
RUN if [ ! -f /var/www/html/api ]; then mkdir -p /var/www/html/api/ ; fi
RUN ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
RUN if [ ! -f /var/www/html/api/composer.json ]; then git clone git@github.com:TiltShiftNL/Tourbuzz-API.git /var/www/html/api/ ; fi