version: "3.2"

services:
  database:
    image: postgis/postgis:10-2.5-alpine
    networks:
        - tourbuzz
    environment:
      POSTGRES_USER: tourbuzz
      POSTGRES_PASSWORD: insecure

  api:
    build: .
    networks:
        - tourbuzz
    ports:
      - "80:80"
    depends_on:
      - database
    environment:
      TOURBUZZ__ENVIRONMENT: "acc."
      TOURBUZZ__DATABASE_HOST: "database"
      TOURBUZZ__DATABASE_PORT: "5432"
      TOURBUZZ__DATABASE_NAME: "tourbuzz"
      TOURBUZZ__DATABASE_USER: "tourbuzz"
      TOURBUZZ__DATABASE_PASSWORD: "insecure"
      TOURBUZZ__MESSAGEBIRD_ENABLE: "true"
      TOURBUZZ__MESSAGEBIRD_API_KEY: "insecure"
      TOURBUZZ__TRANSLATE_API_KEY: "insecure"
      TOURBUZZ__SENDGRID_API_KEY: "insecure"

networks:
  tourbuzz:
    driver: bridge